### ISSUE TITLE
Status of sensor is always "unknown"

### ISSUE THREAD

**Issue by Ra72xx** [Bouni/drkblutspende#1]
Maybe I'm missing something, but I can't get this integration to work. I get lots of hits when entering the values at the webpage, but the integration in homeassistant only always gives the value "unknown".

```
- platform: drkblutspende
  zipcode: 12345
  #radius: 25
  #lookahead: 93
  #county_id: 12345, 12345
```
Commented lines are values I also tried.
No hint in the logfile what goes wrong here.

**Comment by Bouni** [comment]
I guess you did try a real zipcode, not 12345!?

**Comment by Ra72xx** [comment]
Yeah, I tried some anonymity ;-). Some real-life example:

```
- platform: drkblutspende
  zipcode: 12203
  #radius: 15
  #lookahead: 31
  #county_id: 09184, 09162
```
The original web page returns results for that zip code. The sensor of the integration shows nothing in my installation:

![Bildschirmfoto vom 2020-05-24 20-32-49](https://user-images.githubusercontent.com/3582007/82761930-223e8c80-9dfe-11ea-92a8-471cffdd545b.png)
 
The log doesn't give any hint concerning the integration.

**Comment by Bouni** [comment]
I just found the bug, not configured values are set to None and that is put into the query URL which results in a 404 from blutspendeservice.net
I push a fixed version within the next hour or so.

**Comment by Ra72xx** [comment]
Thanks!

**Comment by Bouni** [comment]
OK, new version is available via HACS, pleas test and let me know if it works for you!

**Comment by Ra72xx** [comment]
Seems to work, thanks.
The sensor only displays the next possible date and not all dates within the given timeframe, I assume?

**Comment by Bouni** [comment]
Exactly, just the next date. Maybe I could add the next date after that as a attribute :thinking:
