### ISSUE TITLE
Missing version key in manifest file

### ISSUE THREAD

**Issue by temesinko** [Bouni/drkblutspende#2]
The following warning is raised in Home Assistant >= 2021.3:

```
No 'version' key in the manifest file for custom integration 'drkblutspende'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'drkblutspende'
```

#### More information

* https://www.home-assistant.io/blog/2021/03/03/release-20213/
* https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by Bouni** [comment]
Fixed with release 0.1.4
