### ISSUE TITLE
Show signup link

### ISSUE THREAD

**Issue by Bouni** [Bouni/drkblutspende#4]
Hi Bouni.

Kannst du auch den passenden Link immer mit ausgeben lassen?

Würde gerne auch den passenden Anmeldelink mit anzeigen lassen. Mit einem Klick aus dem LoveLace-Dashboard gelangt man dann direkt zur Anmeldeseite für den Spendentermin.

_Originally posted by @quarkpanzer in https://github.com/Bouni/drkblutspende/issues/3#issuecomment-1090219896_

**Comment by Bouni** [comment]
@quarkpanzer Bitte erstelle für jeden feature request / bug / ... eine neue issue, sonst verliert man die Übersicht.

Zu deiner Frage, ja das sollte gehen, ich schau's mir an.

**Comment by quarkpanzer** [comment]
Wäre ja ein tolles zusätzliches Feature. ;-)

**Comment by Bouni** [comment]
Ist im 0.1.8 release enthalten!

**Comment by Bouni** [comment]
Hier nochmal die Erklärung aus dem PR:

![image](https://user-images.githubusercontent.com/948965/161981383-0113dadc-4db5-46a3-818f-6632660a97ea.png)

In Verbindung mit der [custom button card](https://github.com/custom-cards/button-card) zum Beispiel so:

```
entity: sensor.blutspende
icon: mdi:blood-bag
icon_height: 64px
label: |
  [[[
     var date = states['sensor.blutspende'].attributes.date || '';
     var start = states['sensor.blutspende'].attributes.start || '';
     var end = states['sensor.blutspende'].attributes.end || '';
     var location = states['sensor.blutspende'].attributes.location || '';
     var city = states['sensor.blutspende'].attributes.city || '';
     var rv = "";
     if(date != '') {
       rv += 'am ' + date + '<br>';
     }
     if(location != '') {
       rv += location + '<br>';
     }
     if(city != '') {
       rv += city + '<br>';
     }
     if(start != '' && end != '') {
       rv += 'von ' + start + ' bis ' + end;
     }
     if(rv != '') {
       return rv;
     } else {
       return "Keine in den nächsten 2 Wochen"
     }
     
  ]]]
name: Blutspende
show_icon: true
show_label: true
show_name: true
styles:
  card:
    - height: 160px
  icon:
    - color: rgb(224, 53, 53)
  label:
    - font-size: 12px
  state:
    - font-size: 12px
tap_action:
  action: url
  url_path: '[[[ var link = states["sensor.blutspende"].attributes.link; return link ]]]'
type: custom:button-card

```

Sieht dann so aus:

![image](https://user-images.githubusercontent.com/948965/161982185-e78dd488-4ec2-4a6c-af88-cf69425f46fe.png)
