### ISSUE TITLE
Integration nicht in HA auffindbar - Wo liegt der Fehler?

### ISSUE THREAD

**Issue by iceweasel1** [Bouni/drkblutspende#6]
Hallo Bouni,

gibt es irgendeine Änderung oder ähnliches, dass das aktuell nicht funktioniert?

Ich bekomme es nicht zum Laufen. Dabei halte ich mich an deine Anleitung. Via HACS "Blutspende" installiert, HA neugestartet, FileEditor geöffnet, die configuration.yaml geöffnet und deinen Beispielcode genommen und auf meine Daten abgeändert. Das heißt, ich hatte meine PLZ genommen, den Radius etwas erhöht und countyid sowie zipfilter komplett entfernt, da ich diese beiden nicht brauchte. Da es nicht ging, deinen Beispielcode nochmals genommen und unverändert eingefügt. Ebenfalls kein Ergebnis.

![Bildschirmfoto 2024-04-03 um 07 21 43](https://github.com/Bouni/drkblutspende/assets/49625256/c6b965f1-9bc9-4813-b825-88d3b4fc1e72)

Einzig, die YAML-Sache quittiert es ohne jeglichen Fehler.

Ich kann es bei keinem Dashboard finden oder einfügen, gleiches gilt auch unter Entwicklerwerkzeuge, Zustände, wenn ich nach der Entität Suche. Ich kann es auch dort nicht finden.

Was mache ich falsch?

Aktuelle HA-Version siehe Anhang.

![Bildschirmfoto 2024-04-03 um 07 23 31](https://github.com/Bouni/drkblutspende/assets/49625256/97feacc1-4a98-40b1-a490-b7cf0d89f352)

Grüße
René

**Comment by Bouni** [comment]
Muss ich mir anschauen

**Comment by Bouni** [comment]
Also für mich funktioniert der Sensor, allerdings gibts ein paar sachen zu beachten:

- Ist der lookahead weit genug eingestellt? (in meinem Fall hab ich jetzt 60 Tage genommen)
- Hast du einen Zip Filter gesetzt der evtl. resultate ausblendet?

Wenn du z.B. mit deiner PLZ den folgenden Link im Browser öffnest wird ein .rss heruntergeladen: https://www.spenderservice.net/termine?term=<DEINE-PLZ>

Darin ist bei mir z.B. nur ein Resultat das ausserhalb meinens PLZ Filters liegt und deshalb bekomm ich den Termin auch nicht in den Sensor.

Und die URL wird automatisch um eine Radius von 5km ergänzt wenn man keinen angiebt.

Ich hoffe das hilft

**Comment by iceweasel1** [comment]
Danke dir noch für die schnelle Rückmeldung vergangener Woche. Ich habe den Fehler mittlerweile gefunden. Der Sitz direkt vor dem Bildschirm. Ich selbst. Wie im Screenshot zu sehen, hatte ich "sensor:" überhaupt nicht stehen. Das war der Fehler des Ganzen. Als ich mich eben an das Thema wieder ran machte, und bei einem anderen geschlossenen Issue hier im Screenshot das mit "sensor:" gesehen hatte, ging die Erleuchtung auf. Kleiner Fehler, große Wirkung. Somit kein Fehler im System bei deiner Anwendung. :-)

**Comment by Bouni** [comment]
@iceweasel1 Sind noch Fragen offen oder warum hast du die Issue nochmals aufgemacht? Falls alles klar ist würde ich sie schliessen

**Comment by iceweasel1** [comment]
Keine weiteren Fragen mehr. Danke. Sorry, dass sollte eigentlich geschlossen sein. Hatte wohl einen Hänger. Ich schließe es hiermit.
